[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache = true
cache_path = "cache"
cache_base_path = "cache"
block_base_fee_per_gas = 1000000000
evm_version = "cancun"

[rpc_endpoints]
taraxa_mainnet = "${TARAXA_MAINNET_RPC_URL}"
taraxa_testnet = "${TARAXA_TESTNET_RPC_URL}"
